version: "3.9"

services:
  wisefood-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wisefood-api
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:7.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data